---
# file: molecule/resources/roles/requirements.yml

- src: https://github.com/jam82/ansible-role-hosts.git
  name: hosts
  version: master

- src: https://github.com/jam82/ansible-role-hostname.git
  name: hostname
  version: master
