---
# role: ansible-role-samba
# file: tasks/ad_admin.yml

- name: "Check account expiry for Administrator"
  shell: |
    set -o pipefail && samba-tool user show Administrator | grep accountExpires | cut -d ' ' -f2
  args:
    executable: /bin/bash
  changed_when: False
  register: samba_admin_expiration_days

- name: "Disable expiry of Administrator account"
  command: samba-tool user setexpiry Administrator --noexpiry
  when: samba_admin_expiration_days.stdout | int > 0
