---
# role: ansible-role-samba
# file: tasks/ad_dns.yml

- name: "Check for reverse DNS entry"
  command: "host {{ ansible_default_ipv4.address }}"
  changed_when: False
  ignore_errors: True
  register: samba_reverse_zone_exists

- name: "Set facts for reverse DNS zone and PTR entry"
  set_fact:
    samba_dc_dns_reverse_zone: "{{ ansible_default_ipv4.address | ipaddr('revdns') | regex_replace('^([0-9]+)\\.(.*)\\.', '\\2') }}"
    samba_dc_dns_reverse_ptr: "{{ ansible_default_ipv4.address | ipaddr('revdns') | regex_replace('^([0-9]+)\\.(.*)', '\\1') }}"

- name: "Restart Samba Server and add reverse lookup entires"
  block:
    - name: "Restart Samba Server"
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ samba_role_vars[samba_role].enabled_services }}"

    - name: "Create reverse lookup zone"
      shell: |
        samba-tool dns zonecreate \
        {{ ansible_hostname + '.' + samba_domain }} \
        {{ samba_dc_dns_reverse_zone }} \
        --username=Administrator \
        --password={{ samba_ad.admin_password }}

    - name: "Create reverse lookup PTR entry for dc"
      shell: |
        samba-tool dns add \
        {{ ansible_hostname + '.' + samba_domain }} \
        {{ samba_dc_dns_reverse_zone }} \
        {{ samba_dc_dns_reverse_ptr }} PTR \
        {{ ansible_hostname + '.' + samba_domain }} \
        --username=Administrator \
        --password={{ samba_ad.admin_password }}
  when: samba_dc_dns_reverse_zone in samba_reverse_zone_exists.stdout
