---
# role: ansible-role-samba
# file: tasks/domain controller.yml

- name: "DC | Check if krb5.conf exists"
  stat:
    path: '/var/lib/samba/private/krb5.conf'
  register: samba_krb5

- name: "DC | Remove /etc/samba/smb.conf if krb5.conf does not exists"
  file:
    path: '/etc/samba/smb.conf'
    state: absent
  when: not samba_krb5.stat.exists | bool

- name: "DC | Alpine | Copy openrc-init-file for domain controller"
  template:
    src: "etc/init.d/samba.j2"
    dest: "/etc/init.d/samba"
    mode: '0755'
  when: ansible_os_family == 'Alpine'

- name: "DC | Provision"
  shell: |
    samba-tool domain provision \
    --server-role=dc \
    --use-rfc2307 \
    --dns-backend={{ samba_ad_dns_backend | upper }} \
    {{ '--site=' + (samba_ad_site | upper) if samba_ad_site_enabled else '' }} \
    --realm={{ samba_ad_realm | upper }} \
    --domain={{ samba_ad_domain | upper }} \
    --adminpass={{ samba_ad_admin_password }}
  args:
    creates: '/var/lib/samba/private/krb5.conf'

- name: "DC | Write smb.conf"
  template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0640'
    validate: testparm -s %s
  notify: restart samba

- name: "DC | Include tasks for resolv.conf configuration"
  include_tasks: resolv.yml

- name: "DC | Copy Kerberos Configuration to /etc"
  copy:
    src: '/var/lib/samba/private/krb5.conf'
    dest: '/etc/krb5.conf'
    remote_src: yes

- name: "DC | Include tasks for AD DNS configuration"
  include_tasks: dns.yml

- name: "DC | Disable expiry of Administrator account"
  command: samba-tool user setexpiry Administrator --noexpiry
  changed_when: False

- name: "DC | Set default password expiration period and minimum length"
  command: |
    samba-tool domain passwordsettings set
    --complexity={{ samba_ad_pwd_complexity }}
    --min-pwd-age={{ samba_ad_pwd_min_age }}
    --max-pwd-age={{ samba_ad_pwd_max_age }}
    --min-pwd-length={{ samba_ad_pwd_min_len }}
    --history-length={{ samba_ad_pwd_history_len }}
  changed_when: False
