---
# role: ansible-role-samba
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: True
  pre_tasks:
    - name: "Include variables to converge playbook"
      include_vars: vars.yml
  roles:
    - hosts
    - role: ansible-role-samba
